### ISSUE TITLE
The extention was removed from chrome. Can you put it back up. Thanks.

### ISSUE THREAD

**Issue by RahulS132** [fhuhne/CR-Unblocker#1]

**Comment by fhuhne** [comment]
Google removed this extension from the chrome store. It is unlikely a reupload will stay online :(

I'd distribute this with a separate download, but I don't do a lot with chrome and could not find a way to distribute this outside the store. If you know a way let me know.

**Comment by julianoce** [comment]
Hi, so I was able to put on Google Chrome (without chrome store since they deleted the extension). I've just made some minor changes and it worked well. People will have to add the extension outside the store. How can I contribute?

**Comment by fhuhne** [comment]
Just create a pull request with the required changes. I couldn't get the extension installed at all, so I'm happy with contributions :)

**Comment by julianoce** [comment]
Nice! I will make this as soon as possible :) Thanks!

**Comment by andrei399** [comment]
Hi, it's been a month did you upload it?

**Comment by alan1420** [comment]
@andrei399 extract it into a folder, then from Extensions you can turn on Developer mode and Load unpacked
you can build it on your own if you want
@fhuhne maybe on the next release you can provide the compiled version
[extension.zip](https://github.com/fhuhne/CR-Unblocker/files/5169567/extension.zip)

**Comment by julianoce** [comment]
@andrei399 I did make a pull request, like more than a month ago, but now im seeing that this pull request has been redirect for the other owner of the code (the one that you probably forked). Everytime I try to make a pull request it redirects for the code you forked.

**Comment by julianoce** [comment]
@andrei399 You can check that the pull request was made in https://github.com/cAstraea/CR-Unblocker

**Comment by andrei399** [comment]
@julianoce thanks, i just downloaded it and it works great! Thanks for even providing the zip file because for some reason i missed the email 5 days ago and i searched a lot to find how to download pull requests(I'm very new to github). Again thank you a lot

**Comment by fhuhne** [comment]
Oh, I was wondering why there was no pull request. This is not a fork of the cAstraea reprository, but github messed up the connection after the original repo got deleted. I'll take a look into this the next couple of days. Thank you :)

So there really is no way around the developer mode? Thats sad :(

**Comment by EsmailELBoBDev2** [comment]
here we go https://github.com/fhuhne/CR-Unblocker/pull/7 :)

**Comment by fhuhne** [comment]
Starting with Release 3.0.0 I introduced a github actions workflow adding the zip file to the release, I guess that should be the it for this issue.
