### ISSUE TITLE
Access to content is lost on logging in

### ISSUE THREAD

**Issue by kuraikage** [fhuhne/CR-Unblocker#11]
I was watching some content using the plugin with ads and then I decided to get premium to avoid ads but content gets blocked if I log in. The plugin seems to be working fine as long as I am not logging in to my account

**Comment by fhuhne** [comment]
This is due to Crunchyroll forcing their Beta for logged in users. This extension is broken in Beta, see #5

**Comment by kuraikage** [comment]
Ah, I had a feeling it had something to do with the beta version. Thanks for the quick response.
