### ISSUE TITLE
Working Update for CR Beta

### ISSUE THREAD

**Issue by Ashesh3** [fhuhne/CR-Unblocker#12]
Created an updated addon with a new working method, for Crunchyroll Beta: https://github.com/Ashesh3/CR-Unlocker-Reborn

Let me know your thoughts on the method and if it helped!

**Comment by fhuhne** [comment]
I have tested this locally and I'm amazed at how simple the solution really was in the end.

Do you want to keep your version running or should I transfer your changes into this project? If you want to "take over" I'd push an update for current users to inform them about the new extension (as soon as it is available on the addon store).

**Comment by Ashesh3** [comment]
> I have tested this locally and I'm amazed at how simple the solution really was in the end.
> 
> Do you want to keep your version running or should I transfer your changes into this project? If you want to "take over" I'd push an update for current users to inform them about the new extension (as soon as it is available on the addon store).

Hey, It'd be great if you transfer the changes over to this project!
I just wanted to get the solution out there and see if it works for others, which it seems to!
I think it'll be best for the userbase if you update this project since many people are already using you addon :) 


I'm just curious about one thing, are you going to let users specify their own proxy.. or would the current US server which everyone uses for tokens (cr-unblocker.us.to) will be changed to act as a socks proxy?

**Comment by mirh** [comment]
The addon is no more on mozilla's addons website.

**Comment by Ashesh3** [comment]
> The addon is no more on mozilla's addons website.

The addon is waiting a review from the Mozilla store and will be live shortly. Check back in sometime.

**Comment by Ashesh3** [comment]
@mirh extension is approved, you can install and test it now.

**Comment by Cheos137** [comment]
Works like a charm for me

**Comment by fhuhne** [comment]
> > I have tested this locally and I'm amazed at how simple the solution really was in the end.
> > Do you want to keep your version running or should I transfer your changes into this project? If you want to "take over" I'd push an update for current users to inform them about the new extension (as soon as it is available on the addon store).
> 
> Hey, It'd be great if you transfer the changes over to this project! I just wanted to get the solution out there and see if it works for others, which it seems to! I think it'll be best for the userbase if you update this project since many people are already using you addon :) I'd also like to thank you and @tomo0611 for helping me come up with this solution!
> 
> I'm just curious about one thing, are you going to let users specify their own proxy.. or would the current US server which everyone uses for tokens (cr-unblocker.us.to) will be changed to act as a socks proxy?

Alright, I'll push an update to the add-on soon then. I've already set up a socks proxy on cr-unblocker.us.to, but I think I like your suggestion to make this an option for the user, in case anyone has privacy concerns or similar.

**Comment by fhuhne** [comment]
Finally got around to release an update including this method, I tried to combine it with the existing code to support non logged in users on Crunchyroll Classic.

Once again, thanks a lot @Ashesh3 and @tomo0611, without you guys we wouldn't have this update :)
