### ISSUE TITLE
No longer working on classic site

### ISSUE THREAD

**Issue by Jules-A** [fhuhne/CR-Unblocker#14]
Stopped working ~8 days ago.

**Comment by fhuhne** [comment]
The classic endpoint returns a json with error code 1015, which usually indicates rate limiting. It could also be from an expired device id, but I can't test this right now.

Unfortunately I'm not able to invest much time into this issue before next weekend, my only advice is to use Beta for now.

**Comment by Jules-A** [comment]
Hmm... navigating on beta is borderline unusable... Is is possible to get a way to disable region switching for classic site only (to avoid the notification spam that the addon isn't working) in options?

**Comment by Jules-A** [comment]
Well crap... Looks like they got rid of the classic site for good...

**Comment by mirh** [comment]
They are really going hard at cutting old branches. 
https://www.crunchyroll.com/forumtopic-1076681/announcement-forum-legacy-features-going-away-on-november-1st-2022

**Comment by fhuhne** [comment]
Oh wow, I did not expect this change to happen so suddenly. It was inevitable, but comes as a surprise now.

**Comment by fhuhne** [comment]
@Jules-A do you have any issues with the new page and this add on? I get a different set of shows looking at the alphabetical list.

**Comment by Jules-A** [comment]
> @Jules-A do you have any issues with the new page and this add on? I get a different set of shows looking at the alphabetical list.

I was getting "There was an issue loading the page. Please refresh it." message and wasn't able to load the page until I disabled the extension. It looks like it's not doing that anymore with it enabled but I haven't checked if it's giving me a US session yet.
