### ISSUE TITLE
crunchyroll doesnt loads 

### ISSUE THREAD

**Issue by XtremeChan** [fhuhne/CR-Unblocker#16]
![image](https://user-images.githubusercontent.com/94456740/199441064-09cae12b-a820-4f05-90a9-a1f282752d4a.png)

**Comment by fhuhne** [comment]
Hi,

WidevineCdm is a browser module for DRM protection. Is it working when the Unblocker is removed? I can't reproduce this issue on my side so I have no idea whats going on :(

Since the unblocker only redirects the token request all other functionality should be unaffected.

**Comment by Diapolo10** [comment]
I don't know if this helps, but while I'm not getting that banner, recently every once in a while CR refuses to load video (Firefox). The weirdest thing is, when I

1. Open the developer console (F12),
2. Make sure the console output is visible,
3. Have the console take half the screen, and
2. Refresh the page

...it starts working again? And just refreshing the page normally does nothing. Very odd.

There's a plethora of errors in the console, mostly related to CORS IIRC, and I had to disable Firefox strict mode just to get it to work on this page.

Haven't had to uninstall the extension, at least.

**Comment by XtremeChan** [comment]
> Hi,
> 
> WidevineCdm is a browser module for DRM protection. Is it working when the Unblocker is removed? I can't reproduce this issue on my side so I have no idea whats going on :(
> 
> Since the unblocker only redirects the token request all other functionality should be unaffected.



> 

this works
