### ISSUE TITLE
Site doesn't load

### ISSUE THREAD

**Issue by johnSeed65** [fhuhne/CR-Unblocker#18]
Crunchyroll website is stuck on loading while the extension is enabled the moment it is disabled it starts displaying content back again.
Tried reloading page multiple times.

While it is enabled->
![Capture](https://user-images.githubusercontent.com/107793471/213700977-c210ab58-3a81-43ce-8592-eb6abb5a298d.PNG)

**Comment by fhuhne** [comment]
Thanks for the report, this behavior is known to be caused by the proxied token request not getting through. I'll take a look into it as soon as I got time for it!

**Comment by fhuhne** [comment]
The proxy server lost all outgoing internet connectivity, I restarted the instance and traffic seems to be normal again. Thanks again for the report :)

**Comment by johnSeed65** [comment]
> The proxy server lost all outgoing internet connectivity, I restarted the instance and traffic seems to be normal again. Thanks again for the report :)

No problem & thanks for this extension.
