### ISSUE TITLE
Suggestion: Migrate to APK for Android

### ISSUE THREAD

**Issue by AlvaWayfarer** [fhuhne/CR-Unblocker#19]
First of all, i would like to offer my deepest gratitude to the devs for creating this magnificent tools to help us fellow weebs in the 3rd world country. I have a suggestion as stated in the title above since i really like using the crunchyroll apk more rather than in the browser, i think that it would be a great idea to release the standalone apk version of this extension. Thank you!

**Comment by Atemu** [comment]
Such a thing is technologically very hard to implement (a whole different project entirely) and/or legally questionable.

This is an add-on for browsers; it can't really be ported to other environments.

**Comment by fhuhne** [comment]
As Atemu already said, this is not possible. Patching and distributing the original APK would be illegal and the only alternative is to run some kind of local VPN service that intercepts the call to the token endpoint just like this extension does. That however would be an insane amount of work compared to this browser extension.
