### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by omar-mohy** [fhuhne/CR-Unblocker#2]

**Comment by Atemu** [comment]
Does Mozilla allow you to do install non-blessed addons in regular Firefox on Android yet?

I use Nightly with a custom addon collection to work around Mozilla's arbitrary limitation and the addon works as expected there.

**Comment by fhuhne** [comment]
As far as I know we are still limited to these "approved" addons :(

**Comment by Omar-Mohy** [comment]
> Does Mozilla allow you to do install non-blessed addons in regular Firefox on Android yet?
> 
> I use Nightly with a custom addon collection to work around Mozilla's arbitrary limitation and the addon works as expected there.

Can you please tell me how?

**Comment by Atemu** [comment]
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by Atemu** [comment]
Though note that using nightly comes with its own slew of problems and is only recommended for advanced users (as the article states).

Don't take this personally but, if you couldn't google that article yourself, you probably shouldn't be using Nightly.
