### ISSUE TITLE
Add documentation on how to install CR-Unblocker on Android

### ISSUE THREAD

**Issue by BlexToGo** [fhuhne/CR-Unblocker#23]
Hi there!

First of all: Thank you very much for developing this add-on and making it open source 🙇‍♂️
The readme file mentions that the CR-Unblocker add-on also works on Android
https://github.com/fhuhne/CR-Unblocker/blob/6b316311b7d6719c06bbfbdd69bfda45080b3113/README.md#L9
which is totally correct. However, in the standard [Firefox App](https://play.google.com/store/apps/details?id=org.mozilla.firefox) for Android, it's only possible to install recommended add-ons. When trying to install CR-Unblocker via its [Firefox add-ons page](https://addons.mozilla.org/en-US/firefox/addon/crunchy-unblocker/), the button is disabled and it says 
> To find add-ons compatible with Firefox for Android, [click here](https://addons.mozilla.org/en-US/android/).

So I searched for a way to install non-recommended add-ons on Android and followed [this guide on the Mozilla blog](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) which requires the use of [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) and the creation of an add-on collection. Following that guide, I could successfully install the CR-Unblocker add-on in my Firefox Nightly App on my Android device.
I think a hint to this process regarding Firefox Nightly and an add-on collection would be nice, since I don't think it's obvious that the process is different and more complicated than on desktop.

Thanks
Blex

**Comment by fhuhne** [comment]
Hi! Thanks for the suggestion. That mention in the readme is from old times where it was possible to install the extension without any workaround. I kept it that way hoping Mozilla will allow more extensions soon - this obviously never happened. I agree it makes sense to add a guide for other users who are interested in this.

**Comment by fhuhne** [comment]
I took a look into the current state and apparently Firefox Beta also works now. I guess the support pages are a better link than the old blog article: https://support.mozilla.org/en-US/kb/extended-add-support

If you want you can create a PR for a readme including the link, otherwise I'll add it for the next release :)

**Comment by mirh** [comment]
Are the recent improvements in any way pertinent to this?
https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/
