### ISSUE TITLE
CR-Unblocker has encountered an error

### ISSUE THREAD

**Issue by Pulkit2002** [fhuhne/CR-Unblocker#3]
I am getting this error since yesterday.
![image](https://user-images.githubusercontent.com/65767659/104559395-57883b00-566a-11eb-98f7-22567d7277de.png)

**Comment by fhuhne** [comment]
Hi, is this still happening? There were some issues with the server yesterday.

**Comment by Pulkit2002** [comment]
Yes its working now , Thanks , btw I was trying to make this extension work on android , I downloaded Kiwi Browser and installed the extension , and it seems to be working as I can access shows that are not available in my region on kiwi browser , the only problem is streaming is not starting , it keeps buffering at start of video with black screen , i was curious if it has something to do with extension or the browser itself (I have fast net and I am using 5Ghz Band for Wifi (300 Mbps Download and Upload) , I have also tried leaving it buffering for 15-20 mins to no avail , so if you provide me with any helpful advice , it would be grateful.
