### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by LeXoLz** [fhuhne/CR-Unblocker#32]
Using the extension makes crunchyroll unable to load
![Screenshot_51](https://github.com/fhuhne/CR-Unblocker/assets/86895040/2efaefd6-66f5-470a-ac4d-6bc623e4a73f)

**Comment by TheRedNet** [comment]
Same error

**Comment by LeXoLz** [comment]
Fixed it by disabling every protection on firefox.
