### ISSUE TITLE
Fails to work with Firefox Nightly 87.0a1

### ISSUE THREAD

**Issue by palopezv** [fhuhne/CR-Unblocker#4]
I noticed that the region switch stopped working with Firefox Nightly 87.0a1 (2021-02-20) or maybe sometime last week. Firefox 85.0.2 works fine, but this breakage may drip down to release.

**Comment by Marocco2** [comment]
Firefox Nightly 87.0a1 (2021-02-22) here.
Everything is working as intended. Not sure why do you face this issue

**Comment by palopezv** [comment]
@Marocco2 Geolocation maybe? I'm in South America while you are in Europe, I posit?

**Comment by palopezv** [comment]
OK, I think I've got it. The things I'm interested only show up if you force US English as site language but CR detects my location and defaults to latam Spanish. I wonder if the extension could force this along with the US cookie. (I'm null when it comes to javascript).

**Comment by fhuhne** [comment]
That should be easy to implement, as the language is stored in another cookie. I would make it a toggle though, because not everyone may want this behaviour. I'll take a look into this next weekend and, if there are no further steps involved, implement it right away.

**Comment by fhuhne** [comment]
As far as I can tell language is now a profile setting and no longer cookie based. I might add a note in the next update about language settings to make it more apparent that this is required.
